name: MCBouncer
version: 1.0
author: MCBouncer Staff
website: http://www.mcbouncer.com/
main: com.mcbouncer.plugin.MCBouncer
description: MCBouncer is a cloud-based ban suite and protection program that is modular, unbiased, and fair to its users.
commands:
  ban:
    description: 'Ban a username'
    usage: '/<command> playername [reason]'
    aliases: ['mcb-ban']
  unban:
    description: 'Unban a username'
    usage: '/<command> playername'
    aliases: ['mcb-unban']
  banip:
    description: 'Ban an IP'
    usage: '/<command> playername/IP [reason]'
    aliases: ['mcb-banip']
  unbanip:
    description: 'Unban an IP'
    usage: '/<command> playername/IP'
    aliases: ['mcb-unbanip']
  lookup:
    description: 'See all bans by a username'
    usage: '/<command> playername'
    aliases: ['mcb-lookup']
  kick:
    description: 'Kick a user from the server'
    usage: '/<command> playername [reason]'
    aliases: ['mcb-kick']
  mcbouncer:
    description: 'MCBouncer commands'
    usage: '/<command> [help|version|reload]'
    aliases: ['mcb']
  addnote:
    description: 'Adds a note'
    usage: '/<command> playername note'
    aliases: ['mcb-addnote']
  removenote:
    description: 'Removes a note'
    usage: '/<command> noteid'
    aliases: ['mcb-remotenote', 'delnote', 'mcb-delnote']
